name: run-tests
run-name: running tests on pr by ${{ github.actor }}
env:
 SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_OF_SLIM5}}
 HOSTNAME: ${{ secrets.HOSTNAME  }}
 USER_NAME: ${{ secrets.USER_NAME  }}
on: workflow_dispatch
jobs:
  Testtt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create Dir
        run: |
         echo "$PRIVATE_KEY"
         echo "$USER_NAME"
         echo "$HOSTNAME"
         echo "$PRIVATE_KEY" > .ssh/id_rsa && chmod 600 private_key
         echo "KK"
         ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
         mkdir Helloooooo '
